### ISSUE TITLE
PRACTICA DE ELICITACION DE REQUISITOS

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/practica-de-elicitacion-de-requisitos-equipo-fglr#1]
[REPORTEDEPRACTICA_ELICITACION.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-elicitacion-de-requisitos-equipo-fglr/files/7567915/REPORTEDEPRACTICA_ELICITACION.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación 30/30

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/143179135-36e78a79-12c1-46a4-8f8f-f484b6b92648.png)
La redacción de los requisitos debe ser en infinitivo

**Comment by josealfredo79** [comment]
deben ser concretos, concisos la redacción de los requisitos

**Comment by Rmz-Rigo** [comment]
[REPORTEDEPRACTICA_ELICITACION_CORREGIDO.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-elicitacion-de-requisitos-equipo-fglr/files/7605433/REPORTEDEPRACTICA_ELICITACION_CORREGIDO.pdf)

**Comment by Rmz-Rigo** [comment]
Buenas tardes ing, ya se corrigió lo que usted indicó, gracias...

**Comment by josealfredo79** [comment]
Bien hecho y revisado
